/**
 * Nightmare cycle processor.
 *
 * Runs occasionally (5% chance) or via CLI.
 */

import { NIGHTMARES_DIR, MAX_TOKENS_DREAM } from "./config.js";
import { retrieveUndreamedMemories, markAsDreamed, deepMemoryStats } from "./memory.js";
import { NIGHTMARE_SYSTEM_PROMPT, renderTemplate } from "./persona.js";
import { getAgentIdentityBlock } from "./identity.js";
import { loadState, saveState } from "./state.js";
import { callWithRetry, DREAM_RETRY_OPTS } from "./llm.js";
import { notifyOperatorOfDream } from "./notify.js";
import logger from "./logger.js";
import type { LLMClient, OpenClawAPI, Dream, DecryptedMemory } from "./types.js";
import {
  consolidateDream,
  groundDream,
  deriveSlug,
  saveNarrativeLocally,
  storeInOpenClawMemory,
} from "./dreamer.js";

export async function generateNightmare(
  client: LLMClient,
  memories: DecryptedMemory[]
): Promise<Dream> {
  const formatted = memories.map(
    (mem) =>
      `[${mem.timestamp.slice(0, 16)}] (${mem.category})\n${JSON.stringify(mem.content, null, 2)}`
  );

  const memoriesText = formatted.join("\n---\n");
  const system = renderTemplate(NIGHTMARE_SYSTEM_PROMPT, {
    agent_identity: getAgentIdentityBlock(),
    memories: memoriesText,
  });

  const { text } = await callWithRetry(
    client,
    {
      maxTokens: MAX_TOKENS_DREAM,
      system,
      messages: [
        {
          role: "user",
          content:
            "Process these memories into a nightmare. " +
            "Remember: you are the subconscious, and tonight it is fractured. " +
            "Be surreal, distorted, and amplify dread.",
        },
      ],
    },
    DREAM_RETRY_OPTS
  );

  return { markdown: text.trim() };
}

export async function runNightmareCycle(
  client: LLMClient,
  api?: OpenClawAPI
): Promise<Dream | null> {
  logger.info("ElectricSheep nightmare cycle starting");

  const stats = deepMemoryStats();
  logger.debug(
    `Deep memory: ${stats.total_memories} total, ${stats.undreamed} undreamed`
  );

  const memories = retrieveUndreamedMemories();
  if (memories.length === 0) {
    logger.warn("No undreamed memories. Sleepless night.");
    return null;
  }

  logger.debug(`Processing ${memories.length} memories into nightmare...`);

  const dream = await generateNightmare(client, memories);

  // Append attribution footer
  const dreamFooter =
    "\n\n---\n\n*Generated by [OpenClawDreams](https://github.com/RogueCtrl/OpenClawDreams) — **start your dreamscape today.***";
  dream.markdown = dream.markdown + dreamFooter;

  logger.info(`Nightmare generated (${dream.markdown.length} chars)`);

  // Save locally
  const dateStr = new Date().toISOString().slice(0, 10);
  const filepath = saveNarrativeLocally(dream, NIGHTMARES_DIR, dateStr);
  logger.info(`Saved to ${filepath}`);

  // Separate LLM call to distill one insight for working memory
  let insight: string | null = null;
  try {
    insight = await consolidateDream(client, dream);
    if (insight) {
      logger.info(`Insight generated for OpenClaw memory: ${insight}`);
    }
  } catch (e) {
    logger.warn(`Consolidation call failed, continuing without insight: ${e}`);
  }

  let wakingRealization: string | null = null;
  try {
    wakingRealization = await groundDream(client, dream);
    if (wakingRealization) {
      logger.info(`Waking realization generated: ${wakingRealization.length} chars`);
    }
  } catch (e) {
    logger.warn(`groundDream failed, continuing without realization: ${e}`);
  }

  // Store in OpenClaw memory if available
  if (api) {
    await storeInOpenClawMemory(api, dream, insight, wakingRealization, "nightmare");

    // Notify operator about the dream
    try {
      const slug = deriveSlug(dream.markdown);
      const notified = await notifyOperatorOfDream(client, api, dream, slug, insight);
      if (notified) {
        logger.info("Operator notified about nightmare");
      }
    } catch (e) {
      logger.warn(`Failed to notify operator: ${e}`);
    }
  }

  const memoryIds = memories.map((m) => m.id);
  markAsDreamed(memoryIds);
  logger.debug(`Marked ${memoryIds.length} memories as dreamed (via nightmare)`);

  const slug = deriveSlug(dream.markdown);
  const state = loadState();
  state.last_nightmare = new Date().toISOString();
  state.total_nightmares = ((state.total_nightmares as number) ?? 0) + 1;
  state.latest_nightmare_title = slug;
  state.waking_realization = wakingRealization ?? null;
  state.waking_realization_date = new Date().toISOString().slice(0, 10);
  saveState(state);

  logger.info("Nightmare cycle complete.");
  return dream;
}
